name: 'Terraform Apply'
description: ''
inputs:
  terraform_directory:
    description: ''
    required: true
  terraform_version:
    description: ''
    required: true
  client_id:
      description: ''
    required: true
  client_secret:
    description: ''
    required: true
  tenant_id:
    description: ''
    required: true
  subscription_id:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}
        # terraform_wrapper: false

    - name: Terraform Init
      id: init
      run: terraform init
      shell: bash
      working-directory: ${{ inputs.terraform_directory }}

    - name: Terraform Apply
      id: apply
      run: terraform apply -no-color -auto-approve
      shell: bash
      working-directory: ${{ inputs.terraform_directory }}
      env:
        ARM_CLIENT_ID: ${{ inputs.client_id }}
        ARM_CLIENT_SECRET: ${{ inputs.client_secret }}
        ARM_TENANT_ID: ${{ inputs.tenant_id }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.subscription_id }}