name: 'Terraform Plan'
description: ''
inputs:
  terraform_directory:
    description: ''
    required: true
  terraform_version:
    description: ''
    required: true
  client_id:
    description: ''
    required: true
  client_secret:
    description: ''
    required: true
  tenant_id:
    description: ''
    required: true
  subscription_id:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}
        # terraform_wrapper: false

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check -recursive
      shell: bash
      working-directory: ${{ inputs.terraform_directory }}
      continue-on-error: true


    - name: Terraform Init
      id: init
      run: terraform init
      shell: bash
      working-directory: ${{ inputs.terraform_directory }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      shell: bash
      working-directory: ${{ inputs.terraform_directory }}

    - name: Export Azure Login Credentials
      run: |
        echo "ARM_CLIENT_ID=${{ inputs.client_id }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ inputs.client_secret }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ inputs.subscription_id }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ inputs.tenant_id }}" >> $GITHUB_ENV

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      shell: bash
      working-directory: ${{ inputs.terraform_directory }}
